### ISSUE TITLE
Determine MVP and create user story.

### ISSUE THREAD

**Issue by johnlundy94** [kweinerman/project-freshstate#1]

**Comment by kweinerman** [comment]
https://docs.google.com/document/d/1T-DhRjoeiQ8OWnJMGzrRR_iZHCyjTJoJLots_Gs1Gu4/edit#heading=h.iuvcena9ljti

**Comment by kweinerman** [comment]
Marking this done in conjunction with google doc

**Comment by johnlundy94** [comment]
Great stuff man! Sorry for not responding or contributing yet. I have work
until Monday night and then I’ll get on it!
